name: broken links?
'on':
  push:
    branches:
      - "**"
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:  
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: true
