name: Maven Publish

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: central
        server-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        server-password: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Build with Maven
      run: mvn clean package -Dmaven.javadoc.skip=false

    - name: Import signing key
      run: gpg --batch --import ${{ secrets.GPG_SECRET_KEY }}
        
    - name: Publish to Maven Central
      run: mvn -X -Dgpg.passphrase=${{ secrets.PGP_PASSPHRASE }} deploy -DskipTests -Dmaven.javadoc.skip=false
